// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DbService is bound to the Wails frontend. All public methods are callable from TypeScript.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Health returns database connectivity status.
 */
export function Health(): $CancellablePromise<$models.HealthResult> {
    return $Call.ByID(3883206257).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListKinds returns the distinct kind values and counts for a given table.
 */
export function ListKinds(table: string): $CancellablePromise<$models.KindInfo[]> {
    return $Call.ByID(2539934690, table).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListTables returns all Nine Tables with row counts.
 */
export function ListTables(): $CancellablePromise<$models.TableInfo[]> {
    return $Call.ByID(2865018166).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HealthResult.createFrom;
const $$createType1 = $models.KindInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.TableInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
