// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HealthResult is returned by Health().
 */
export class HealthResult {
    "status": string;
    "connected": boolean;
    "table_count": number;
    "timestamp": string;

    /** Creates a new HealthResult instance. */
    constructor($$source: Partial<HealthResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("table_count" in $$source)) {
            this["table_count"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthResult($$parsedSource as Partial<HealthResult>);
    }
}

/**
 * KindInfo is one row in the ListKinds response.
 */
export class KindInfo {
    "kind": string;
    "count": number;

    /** Creates a new KindInfo instance. */
    constructor($$source: Partial<KindInfo> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KindInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): KindInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KindInfo($$parsedSource as Partial<KindInfo>);
    }
}

/**
 * TableInfo is one row in the ListTables response.
 */
export class TableInfo {
    "name": string;
    "row_count": number;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("row_count" in $$source)) {
            this["row_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}
