-- 15_the_ledger.sql
-- Invisible infrastructure. Append-only tick telemetry.
-- Managed by T.A.S.K.S. — compression, retention, cleanup.
-- NOT a domain card. Users never see this directly.

CREATE TABLE the_ledger (
    id          BIGSERIAL PRIMARY KEY,
    kind        TEXT NOT NULL,
    agent_id    TEXT,
    meta        JSONB NOT NULL DEFAULT '{}',
    body        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    -- NO slug, NO title, NO status, NO updated_at.
    -- This is pure telemetry. Append-only. Never updated.
);

COMMENT ON TABLE the_ledger IS 'Invisible infrastructure — tick_log and tick_reports. Append-only, compressible. Managed by T.A.S.K.S., not visible as a domain card.';

-- Kind taxonomy:
-- tick_log      Per-agent per-tick audit entry.
--               meta: tick_number, energy_before, energy_after, tier,
--                     model_used, llm_called, action_taken
--               body: action_detail
-- tick_report   Per-tick cycle telemetry.
--               meta: total_agents, active, idle, dormant, llm_calls,
--                     budget_used, budget_max, top_actors, energy_snapshot
-- rollup_daily  Compressed daily summary per agent (generated by retention job).
--               meta: total_ticks, total_actions, avg_energy, tier_changes,
--                     llm_calls, notable_events[]
-- rollup_monthly Monthly summary (generated by retention job).

CREATE INDEX idx_ledger_kind ON the_ledger(kind);
CREATE INDEX idx_ledger_agent ON the_ledger(agent_id) WHERE agent_id IS NOT NULL;
CREATE INDEX idx_ledger_created ON the_ledger(created_at DESC);
CREATE INDEX idx_ledger_kind_agent_created ON the_ledger(kind, agent_id, created_at DESC);

-- No triggers. No wikilink extraction. No updated_at.
-- Pure INSERT performance.
